### ISSUE TITLE
`Python Exception <KeyError>: 'layerId'` With Shapefile to Socrata Workflow

### ISSUE THREAD

**Issue by seabre** [socrata/connectors#30]
We have several workflows that use the Shapefile to Socrata Workflow. No changes have been made on our end. Has the Socrata's API for this changed?

#### FME Log Output

```
FME_END_PYTHON: evaluating python script from string...
Python Exception <KeyError>: 'layerId'
...
```

#### Request Response That Should Have `layerId` But Doesn't

I inspected the output of `response_summary['layers']` that is used to populate the `blueprint` dictionary inside the `resplaceWithShapeScanResults` function. The following is the output, which *should* have a key/value pair for `layerId`, but doesn't. I replaced the value of the 4x4, but if you need an example affected dataset 4x4, I can provide that:

```python
[   {   u'name': u'fake-data',
        u'referenceSystem': u'NAD_1983_StatePlane_Tennessee_FIPS_4100_Feet'}]
```

Also, making sure @aplannersguide is looped in.

**Comment by PeterAustinMoore** [comment]
Thank you for noting this - 

This can be fixed by changing a couple lines in the `resplaceWithShapeScanResults` function from:
`  blueprint = {
    'layers': [
      {
        'layerId': layer['layerId'],
        'name': layer['name']
      } for layer in response_summary['layers']]
  }`

to:
`blueprint = {
    'layers': response_summary['layers']
  }`

**Comment by seabre** [comment]
Closing. This actually fixes my issue, but as it turns out, the Shapefile -> Socrata workflow here isn't exactly the same workflow I'm using from Socrata.
